@startuml
'https://plantuml.com/class-diagram

class PaddingBox {
Component component
Integer paddingTop
Integer paddingBottom
Integer paddingLeft
Integer paddingRight
Boolean show
Component.maximumSize dim
UI.bounds total
Spacer top
Spacer left
Spacer right
Spacer bot
BoxPanel middleGroup
}

@enduml