@startuml
'https://plantuml.com/class-diagram

class TopContainer << (O, #FF7700) >> {
Integer msgCount
String l
BoxPanel messageContainer
ScrollPanel scrollPanel
PaddingBox withPadding
addMessage(lang: Language, msg: String, date: String, isUser: Boolean)
}

@enduml