@startuml
'https://plantuml.com/class-diagram

class WelcomeFrame << (O, #FF7700) >>  {
Img bannerDark
Img bannerLight
Img banner
Flag flagFR
Flag flagEN
Flag flagAL
Flag flagES
Flag flagIT
BoxPanel group
BoxPanel flagsContainer
PaddingBox withPadding

size()
}

@enduml